import React from "react";
import Client from "../views/Client";
import Dashboard from "../views/Dashboard";
import Profile from "../views/Profile";

var routes = [
  {
    path: "/user-profile",
    name: "User Profile",
    icon: "ni ni-single-02",
    component: <Profile />,
    layout: "/in",
    sidebar: false,
  },
  {
    path: "/index",
    name: "Dashboard",
    icon: "ni ni-tv-2",
    component: <Dashboard />,
    layout: "/in",
    sidebar: true,
    postion: 1,
  },
  {
    path: "/user-client",
    name: "Client",
    icon: "ni ni-single-02",
    component: <Client />,
    layout: "/in",
    sidebar: true,
    postion: 2,
  },
  {
    path: "/user-intern",
    name: "Back office",
    icon: "fa fa-users",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 2,
  },
  {
    path: "/abonnement-service",
    name: "Service Abonnement",
    icon: "fa fa-compress",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 3,
  },
  {
    path: "/abonnement-option",
    name: "Option Abonnement",
    icon: "fa fa-expand",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 3,
  },
  {
    path: "/cour",
    name: "Cour",
    icon: "fa fa-book",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 4,
  },
  {
    path: "/categorie",
    name: "Categorie Materiel",
    icon: "ni ni-box-2",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 5,
  },
  {
    path: "/materiel",
    name: "Materiel",
    icon: "fa fa-cube",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 5,
  },
  {
    path: "/salle",
    name: "Salle",
    icon: "ni ni-single-02",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 5,
  },
  {
    path: "/repas",
    name: "Repas",
    icon: "fa fa-cutlery", 
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 6,
  },
  {
    path: "/order",
    name: "Commande",
    icon: "fa fa-shopping-cart",
    component: <Profile />,
    layout: "/in",
    sidebar: true,
    postion: 7,
  },
];
export default routes;
